### ISSUE TITLE
[Tracking] Fiddler Everywhere Docs revamp

### ISSUE THREAD

**Issue by NickIliev** [telerik/fiddler-everywhere-docs#13]
The Fiddler Everywhere documentation is in progress and the tracking issue is meant to track the overall progress of listing all features and functionalities. The documentation will require screenshots for the UI which should be taken on the MAC client.

> **Note:** The screenshots used in the revamp branch are not fina and will be updated after the new release is ready. 

Below is an example of the base navigation tree in the early stages. Ping me for any comments (e.g. about the structure or unlisted features).

The working branch will be deployed via a test Jenkins job and the current state can be seen [here](https://testdocs.telerik.com/fiddler-everywhere/getting-started/installation) (live after a successfully Jenkins build)

- Introduction
	- [x] Introduciton page

- Getting Started,
	- [x] **Requirments - list reqs for Windows, Mac, Linux**
	- [x] **Installation - Installation procedure (download, install, login instructions)**
		1. Windows **(done)**
		2. Mac OS
		3. Linux
	- [x] Configuration
        - [ x] Capture Traffic
	- [x] Inspect Traffic
	- [ ] Edit Traffic
	- [ ] Mock Server Response
	- [ ] Create API request
	- [ ] Collaboration
	- [ ] PRO vs Free  version comparision
- User Guide
	- [x] Fiddler's Main Menu
	     - [x] File
	     	     -  Load Archive **_OK_**
	     	     -  Save Archive **_OK_**
	     	     -  Import Sessions **_OK_**
	     	     -  Export Sessions **_OK_**
	     - [x] Help
	     	     -  Check for updates **_OK_**
	- [x] Settings
	     - [x] **HTTPS** (**_In Progress_**)
	     	     -  Decrypt Secure traffic option (will this option be available )
	     	     -  Add trust certificate option
	     	     -  Export root certificate option
	     	     -  New option to enable HTTPS via the Web Sessions List "PROTOCOL" warning (see  changes made by Nischal)
	     - [x] Connections
	     	     -  "Allow remote connection" option
	     - [x] Gateway
	     - [x] Privacy
	- [x] Saved Sessions
		- [x] Saved Sessions List
		- [ ] Share Sessions
		- [ ] Quotas (paid vs free)
	- [x] Live Traffic
		- [x] Web Sessions List
	              - [x] Web Sessions context menu
	              - [x] Web Sessions toolbar 
	     	            -  [x] Live Traffic (capture switch) 
	     	            -  [x] Stream 
	     	            -  [x]  Decode 
	     	            -  [x] Pause 
	     	            -  [x] Find 
	     	            -  [x] Filter 
	     	            -  [x] **Share** 
	     	            -  [x] Save 
	     	            -  [x] Remove
		- [x] Inspectors tab
	              - [x] Request Inspector (top)
	              - [x] Response Inspector  (bottom)
		- [x] Auto Responder tab
	              - [x] rules editor (left)
	                  - [x] create rule
	                  - [x] match
	                  - [x] actions
	              - [x] queue viewer (right)
	                  - [x] grouping
	                  - [x] enabling
	                  - [x] import
	                  - [x] export
	                  - [x] pass-through
	                  - [x] options
	              - [ ] quotas (paid vs free)
	- [x] Composer
	    - [x] API methods
	    - [x] Testing APIs
	              - Select API method 
	              - Enter URL
	              - Under Headers, enter Authorization Key followed by the request body
	              - Click on Execute
	              - See the Response 

	- [ ] Seeing quota for shared sessions (difference between paid and free version
- Use Cases
	- [ ] _TODO: List articles for specific use stories here_
- Copyright
	- [x] Copyright page
- License
	- [x] License page
- Knowledge Base
	- [x] _Update content_
